### ISSUE TITLE
Feature: support for multiple file extensions

### ISSUE THREAD

**Issue by vranystepan** [nordcloud/serverless-jest-plugin#31]
Hello,
I'd like to use `serverless-jest-plugin` with `ts-jest`, I have functional `serverless.yml` configuration but it would also requires minimal changes in `lib/run-tests.js`.

```yaml
custom:
  jest:
    transform:
      "^.+\\.(t|j)sx?$": "ts-jest"
    preset: ts-jest
    moduleFileExtensions:
      - ts
      - js
      - json
      - node
```

https://github.com/SC5/serverless-jest-plugin/blob/master/lib/run-tests.js#L20 to
```javascript
Object.assign(config, { testRegex: `${functionName}\\.test\\.(j|t)s$` });
```

https://github.com/SC5/serverless-jest-plugin/blob/master/lib/run-tests.js#L25 to
```javascript
const functionsRegex = allFunctions.map(name => `${name}\\.test\\.(j|t)s$`).join('|');
```

Is it ok to submit such PR?
